openapi: 3.0.3

info:
  title: ZimaCube Monitoring API
  version: v2

servers:
  - url: /v2/metrics

security:
  - access_token: []

tags:
  - name: ZimaCube Metrics
    description: Get the service metrics of ZimaCube

paths:
  /:
    get:
      summary: Get the service metrics of ZimaCube
      operationId: getMetrics
      tags:
        - ZimaCube Metrics
      responses:
        "200":
          $ref: "#/components/responses/ResponseZimaCubeMetricsOK"
        "400":
          $ref: "#/components/responses/ResponeBadRequest"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"
    post:
      summary: Add a ssh host to monitor
      operationId: postAddZimaCube
      tags:
        - ZimaCube Metrics
      requestBody:
        $ref: "#/components/requestBodies/AddZimaCube"
      responses:
        "200":
          $ref: "#/components/responses/ResponseOK"
        "400":
          $ref: "#/components/responses/ResponeBadRequest"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"
    delete:
      summary: Delete a ssh connection from monitoring
      operationId: deleteZimaCube
      tags:
        - ZimaCube Metrics
      parameters:
        - name: ip
          in: query
          description: IP address of the server
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/ResponseOK"
        "400":
          $ref: "#/components/responses/ResponeBadRequest"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

components:
  securitySchemes:
    access_token:
      type: apiKey
      in: header
      name: Authorization

  requestBodies:
    AddZimaCube:
      content:
        application/json:
          schema:
            type: object
            properties:
              ip:
                type: string
                description: IP address of the server
                example: "10.0.0.85"
              port:
                type: integer
                description: Port of the server
                example: 22
              username:
                type: string
                description: Username of the server
                example: "root"
              password:
                type: string
                description: Password of the server
                example: "password"

  responses:
    ResponseOK:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"

    ResponeBadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"

    ResponseInternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"

    ResponseZimaCubeMetricsOK:
      description: Metrics of ZimaCube
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Metric"

  schemas:
    BaseResponse:
      properties:
        message:
          description: message returned by server side if there is any
          type: string

    ZimaCubeMetrics:
      properties:
        ip:
          description: IP address of the server
          type: string
        metrics:
          description: Metrics of the server
          type: array
          items:
            $ref: "#/components/schemas/Metric"

    Metric:
      properties:
        name:
          description: Name of the service
          type: string
          example: "zimaos"
        cpu:
          description: CPU usage of the server
          type: string
          example: 0.5%
        max_cpu:
          description: Maximum CPU usage of the server in the last 1 hour
          type: string
          example: 5%
        avg_cpu:
          description: Average CPU usage of the server in the last 1 hour
          type: string
          example: 5%
        mem:
          description: Memory usage of the server
          type: string
          example: 0.5%
        max_mem:
          description: Maximum Memory usage of the server in the last 1 hour
          type: string
          example: 5%
        avg_mem:
          description: Average Memory usage of the server in the last 1 hour
          type: string
          example: 5%
        uptime:
          description: Uptime of the service
          type: string
          example: "1 day 2 hours 3 minutes"
